### ISSUE TITLE
Exception Info: System.DllNotFoundException: Unable to load DLL 'Everything.dll'

### ISSUE THREAD

**Issue by richardmalone** [stax76/Everything.NET#1]
Great start on a decent frontend for Windows' best ever utility.  

I suffered a crash on trying to search anything, but easily fixed by copying across Everything.dll from mpv.net folder. Event Viewer log is below. 

Also, you need to implement right clicking context menus and shift+right click. One of my main uses of Everything is to 'Copy as Path' to then drop into other programmes. 

Thanks for work so far!

```
Application: EverythingFrontend.exe
CoreCLR Version: 5.0.120.57516
.NET Version: 5.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Everything.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at EverythingFrontend.Model.Everything_SetSearch(String lpSearchString)
   at EverythingFrontend.Model.GetItems(String searchText) in D:\Projekte\CS\Everything Frontend\src\Model.cs:line 19
   at EverythingFrontend.ViewModel.Update(String text) in D:\Projekte\CS\Everything Frontend\src\ViewModel.cs:line 43
   at EverythingFrontend.ViewModel.TypeAssistant_Idled(String text) in D:\Projekte\CS\Everything Frontend\src\ViewModel.cs:line 39
   at TypeAssistant.<.ctor>b__5_0(Object p) in D:\Projekte\CS\Everything Frontend\src\TypeAssistant.cs:line 13
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

**Comment by stax76** [comment]
Thanks for the feedback! I forgot to add the DLL. I try finding time improving this app.

Maybe it's possible to show the native File Explorer menu, I can ask the Everything author how it works and I can take a look at the Double Commander source code.

Right now you can double-click to open and select the file in File Explorer. File Explorer supports _Copy as path_ by pressing Shift.

But there is a better power-user way using my _Open with++_ shell extension:

https://github.com/stax76/OpenWithPlusPlus#copy-paths

**Comment by stax76** [comment]
It should be possible to show the native context menu, but it's not completely easy, it would much likely take at least a full day work and personally I'm not sure if I really need this functionality. 🤔

https://www.codeproject.com/Articles/15059/C-File-Browser

**Comment by stax76** [comment]
v1.1 is available

**Comment by richardmalone** [comment]
Thanks @stax76, will try out the new version
